#!/bin/bash

list_remote_branches() {
  git branch -r | while read -r line; do 
    [[ "$line" =~ 'HEAD' || "$line" =~ 'main' ]] && continue; 
    [[ "$line" =~ ^$1/ ]] && echo ${line#$1/} 
  done
}

list_local_branches() {
  git for-each-ref --format='%(refname:short)' refs/heads
}


rebase() {
  tip=main

  echo -n "Rebasing onto $tip: "

  while [ $# -gt 0 ]; do
    echo -n "$1 "
    git merge-base --is-ancestor $tip $1 || { git checkout --quiet $1 && git rebase --quiet $tip; }
    tip=$1
    shift
  done

  echo "[OK]"
}


remote=$(git remote)
echo "remote is set to \"$remote\""

current_branch=$(git branch --show-current)
echo "Currently on branch \"$current_branch\""

declare -A listed_branches
for b in $(<.devcontainer/branches); do
  listed_branches[$b]=1
done

unlisted=""
for b in $(list_remote_branches $remote); do 
  [ -n "${listed_branches[$b]}" ] || unlisted+="$b "
done
[ -n "$unlisted" ] && { echo "Unlisted remote branches:"; for b in $unlisted; do echo "  $b"; done; }


unlisted=""
for b in $(list_local_branches); do 
  [ -n "${listed_branches[$b]}" ] || unlisted+="$b "
done
[ -n "$unlisted" ] && { echo "Unlisted local branches:"; for b in $unlisted; do echo "  $b"; done; }

set -e

echo "Checking out listed branches if not already checked out..."
for b in ${!listed_branches[@]}; do
  git show-ref --quiet refs/heads/$b && continue
  echo "  $b"
  git checkout --quiet --track $remote/$b
done


while read -r line; do 
  [ "x$line" != "x" ] && rebase $line
done < .devcontainer/branches

git checkout $current_branch

if [ $1 == "--push" ]; then

  for b in main ${!listed_branches[@]}; do
    [ $(git rev-parse $b) == $(git rev-parse --quiet $remote/$b 2>/dev/null) ] || git push --force $remote $b:$b 
  done

fi

